# Generated by Django 4.1.5 on 2023-01-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('min_hours_per_week', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'timepiece_contractassignment',
            },
        ),
        migrations.CreateModel(
            name='ContractHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date_requested', models.DateField()),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved')], default=1)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'contracted hours',
                'verbose_name_plural': 'contracted hours',
                'db_table': 'timepiece_contracthour',
            },
        ),
        migrations.CreateModel(
            name='EntryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invoiced', 'Invoiced'), ('not-invoiced', 'Not Invoiced')], default='invoiced', max_length=24)),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference #')),
                ('comments', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField()),
            ],
            options={
                'db_table': 'timepiece_entrygroup',
            },
        ),
        migrations.CreateModel(
            name='HourGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'timepiece_hourgroup',
            },
        ),
        migrations.CreateModel(
            name='ProjectContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('current', 'Current'), ('complete', 'Complete')], default='upcoming', max_length=32)),
                ('type', models.IntegerField(choices=[(1, 'Fixed'), (2, 'Pre-paid Hourly'), (3, 'Post-paid Hourly')])),
            ],
            options={
                'verbose_name': 'contract',
                'db_table': 'timepiece_projectcontract',
                'ordering': ('-end_date',),
            },
        ),
    ]
