# Generated by Django 4.1.5 on 2023-01-14 22:37

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Enter a short code to describe the type of activity that took place.', max_length=5, unique=True)),
                ('name', models.CharField(help_text='Now enter a more meaningful name for the activity.', max_length=50)),
                ('billable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'db_table': 'timepiece_activity',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'timepiece_location',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('approved', 'Approved'), ('invoiced', 'Invoiced'), ('not-invoiced', 'Not Invoiced')], default='unverified', max_length=24)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('seconds_paused', models.PositiveIntegerField(default=0)),
                ('pause_time', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('hours', models.DecimalField(decimal_places=5, default=0, max_digits=11)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='entries.activity')),
                ('entry_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='contracts.entrygroup')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='entries.location')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='crm.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timepiece_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entries',
                'db_table': 'timepiece_entry',
                'ordering': ('-start_time',),
                'permissions': (('can_clock_in', 'Can use Pendulum to clock in'), ('can_pause', 'Can pause and unpause log entries'), ('can_clock_out', 'Can use Pendulum to clock out'), ('view_entry_summary', 'Can view entry summary page'), ('view_payroll_summary', 'Can view payroll summary page'), ('approve_timesheet', 'Can approve a verified timesheet')),
            },
        ),
        migrations.CreateModel(
            name='ActivityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('activities', models.ManyToManyField(related_name='activity_group', to='entries.activity')),
            ],
            options={
                'db_table': 'timepiece_activitygroup',
            },
        ),
        migrations.CreateModel(
            name='ProjectHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='start of week')),
                ('hours', models.DecimalField(decimal_places=5, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))])),
                ('published', models.BooleanField(default=False)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project hours entry',
                'verbose_name_plural': 'project hours entries',
                'db_table': 'timepiece_projecthours',
                'unique_together': {('week_start', 'project', 'user')},
            },
        ),
    ]
