# Generated by Django 4.1.5 on 2023-01-14 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activity_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_group', to='entries.activitygroup', verbose_name='restrict activities to'),
        ),
        migrations.AddField(
            model_name='project',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_business_projects', to='crm.business'),
        ),
        migrations.AddField(
            model_name='project',
            name='point_person',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(limit_choices_to={'type': 'project-status'}, on_delete=django.db.models.deletion.CASCADE, related_name='projects_with_status', to='crm.attribute'),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(limit_choices_to={'type': 'project-type'}, on_delete=django.db.models.deletion.CASCADE, related_name='projects_with_type', to='crm.attribute'),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='user_projects', through='crm.ProjectRelationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('type', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='projectrelationship',
            unique_together={('user', 'project')},
        ),
    ]
